# Copyright: (c) 2019, Booz Allen Hamilton
# Booz Allen Public License v1.0 (see LICENSE or http://boozallen.github.io/licenses/bapl)

# Configure Ambari Agent and SELinux on all servers
- hosts: enk-server
  user: "{{ aws_user }}"
  become: yes
  become_method: sudo
  roles:
  - role: elastic-nifi-kibana-install